# Generated by Django 4.1.8 on 2023-04-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_order_orderitem_ticketclass_remove_ticket_event_and_more"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="discount",
        #     name="EVENT_ID",
        #     field=models.IntegerField(),
        # ),
        # migrations.AlterField(
        #     model_name="discount",
        #     name="id",
        #     field=models.IntegerField(primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.order",
            ),
        ),
    ]
