# Generated by Django 4.1.8 on 2023-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_alter_orderitem_options_alter_discount_event_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        # migrations.AlterField(
        #     model_name="discount",
        #     name="EVENT_ID",
        #     field=models.IntegerField(),
        # ),
        # migrations.AlterField(
        #     model_name="discount",
        #     name="id",
        #     field=models.IntegerField(primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name="orderitem",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
