# Generated by Django 4.2b1 on 2023-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('EVENT_ID', models.IntegerField()),
                ('NAME', models.CharField(max_length=20)),
            ],
        ),
    ]
