# Generated by Django 4.2b1 on 2023-03-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('percent_off', models.CharField(max_length=20)),
                ('CODE', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Quantity_available', models.IntegerField()),
                ('User_ID', models.IntegerField()),
            ],
        ),
    ]
