# Generated by Django 4.2b1 on 2023-03-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_delete_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='DESCRIIPTION',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='NAME',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='EVENT_PHOTO',
        ),
    ]
