# Generated by Django 4.2b1 on 2023-03-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_delete_discount_delete_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ONLINE',
            field=models.CharField(choices=[('t', 'true'), ('f', 'false')], max_length=1),
        ),
    ]
