# Generated by Django 4.2b1 on 2023-03-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_delete_discount_delete_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ONLINE',
            field=models.BooleanField(default=False),
        ),
    ]
