# Generated by Django 4.2b1 on 2023-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ONLINE',
        ),
        migrations.AddField(
            model_name='event',
            name='online',
            field=models.CharField(default='f', max_length=1),
            preserve_default=False,
        ),
    ]
