# Generated by Django 4.2b1 on 2023-04-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_interests_event_user_event_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interests',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='description',
        ),
        migrations.AddField(
            model_name='interests',
            name='ID',
            field=models.IntegerField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
