# Generated by Django 4.2b1 on 2023-04-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_rename_name_interests_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interests',
            old_name='ID',
            new_name='user_id',
        ),
    ]
