# Generated by Django 4.2b1 on 2023-04-06 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0020_alter_interests_user_id_userinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='interest',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='category_name',
            field=models.CharField(default='category', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
