# Generated by Django 4.2b1 on 2023-04-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_remove_event_interests_remove_userinterest_interest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Category',
            new_name='category_name',
        ),
    ]
