# Generated by Django 4.2b1 on 2023-04-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_rename_category_event_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='CATEGORY_ID',
        ),
        migrations.RemoveField(
            model_name='event',
            name='SUB_CATEGORY_ID',
        ),
        migrations.RemoveField(
            model_name='event',
            name='User_id',
        ),
    ]
