# Generated by Django 4.2b1 on 2023-04-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_remove_event_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='locationـid',
        ),
    ]
