# Generated by Django 4.2b1 on 2023-04-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_event_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_image',
        ),
    ]
