# Generated by Django 4.2b1 on 2023-04-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_remove_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='sub_Category',
            field=models.CharField(default='string', max_length=255),
            preserve_default=False,
        ),
    ]
