# Generated by Django 4.2b1 on 2023-04-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_userinterest_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='sub_Category',
        ),
    ]
