# Generated by Django 4.2b1 on 2023-04-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
