# Generated by Django 4.2b1 on 2023-04-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='sub_categories',
            field=models.TextField(default='string'),
            preserve_default=False,
        ),
    ]
