# Generated by Django 4.2b1 on 2023-04-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_userinterest_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='sub_categories',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='sub_Category',
            field=models.CharField(default='string', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_Category',
            field=models.CharField(max_length=20),
        ),
    ]
