# Generated by Django 4.2b1 on 2023-04-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_remove_event_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='User_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
