# Generated by Django 4.2b1 on 2023-04-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_event_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Summery',
            field=models.CharField(default='string', max_length=500),
            preserve_default=False,
        ),
    ]
