# Generated by Django 4.2b1 on 2023-04-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='online',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
    ]
