# Generated by Django 4.2b1 on 2023-04-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_alter_event_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='STATUS',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Live', 'Live'), ('Past', 'Past')], max_length=5),
        ),
    ]
