# Generated by Django 4.2b1 on 2023-04-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='PASSWORD',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Summery',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='User_id',
            field=models.IntegerField(null=True),
        ),
    ]
