# Generated by Django 4.2b1 on 2023-04-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_alter_event_description_alter_event_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
