# Generated by Django 4.2b1 on 2023-04-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
