# Generated by Django 4.2b1 on 2023-04-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0047_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_Category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
