# Generated by Django 4.2b1 on 2023-04-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0048_alter_event_category_name_alter_event_organizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category_name',
            field=models.CharField(default='string', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='string', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_Category',
            field=models.CharField(default='string', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='string', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(default='string', max_length=20),
            preserve_default=False,
        ),
    ]
