# Generated by Django 4.2b1 on 2023-04-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0049_alter_event_id_alter_event_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(to='event.image'),
        ),
    ]
