# Generated by Django 4.2b1 on 2023-04-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0050_image_event_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
