# Generated by Django 4.2b1 on 2023-04-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0052_eventimage_event_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
