# Generated by Django 4.2b1 on 2023-04-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0054_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event'),
            preserve_default=False,
        ),
    ]
