# Generated by Django 4.2b1 on 2023-04-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0056_event_image2_event_image3_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
