# Generated by Django 4.2b1 on 2023-04-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0057_event_image4_event_image5_event_image6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image6',
        ),
    ]
