# Generated by Django 4.2b1 on 2023-04-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0062_event_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image4'),
        ),
    ]
