# Generated by Django 4.2b1 on 2023-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0063_event_image1_alter_event_image2_alter_event_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image1',
        ),
        migrations.AddField(
            model_name='event',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image5'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category_name',
            field=models.CharField(choices=[('Category', 'Category'), ('Auto, Boat & Air', 'Auto, Boat & Air'), ('Business & Professional', 'Business & Professional'), ('Charity & Causes', 'Charity & Causes'), ('Community & Culture', 'Community & Culture'), ('Family & Education', 'Family & Education'), ('Fashion & Beauty', 'Fashion & Beauty'), ('Film, Media & Entertainment', 'Film, Media & Entertainment'), ('Food & Drink', 'Food & Drink'), ('Government & Politics', 'Government & Politics'), ('Health & Wellness', 'Health & Wellness'), ('Hobbies & Special Interest', 'Hobbies & Special Interest'), ('Home & Lifestyle', 'Home & Lifestyle'), ('Music', 'Music'), ('Performing & Visual Arts', 'Performing & Visual Arts'), ('Religion & Spitituality', 'Religion & Spitituality'), ('School Activities', 'School Activities'), ('Science & Technology', 'Science & Technology'), ('Seasonal & Holiday', 'Seasonal & Holiday'), ('Sports & Fitness', 'Sports & Fitness'), ('Travel & Outdoor', 'Travel & Outdoor'), ('Other', 'Other')], default='Category', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Type', 'Type'), ('Appearance or Singing', 'Appearance or Singing'), ('Attraction', 'Attraction'), ('Camp, Trip, or Retreat', 'Camp, Trip, or Retreat'), ('Class, Training, or Workshop', 'Class, Training, or Workshop'), ('Concert or Performance', 'Concert or Performance'), ('Conference', 'Conference'), ('Convention', 'Convention'), ('Dinner or Gala', 'Dinner or Gala'), ('Festival or fair', 'Festival or fair'), ('Game or Competition', 'Game or Competition'), ('Meeting or Networking Event', 'Meeting or Networking Event'), ('Party or Social Gathering', 'Party or Social Gathering'), ('Race or Endurance Event', 'Race or Endurance Event'), ('Rally', 'Rally'), ('Screening', 'Screening'), ('Seminar or Talk', 'Seminar or Talk'), ('Tour', 'Tour'), ('Tournment', 'Tournment'), ('Tradeshow, Consumer Show, or Expo', 'Tradeshow, Consumer Show, or Expo'), ('Other', 'Other')], default='Type', max_length=50),
        ),
    ]
