# Generated by Django 4.2b1 on 2023-04-26 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0068_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
