# Generated by Django 4.2b1 on 2023-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0071_eventlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Publish',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=10),
            preserve_default=False,
        ),
    ]
