# Generated by Django 4.2b1 on 2023-04-26 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0075_alter_event_venue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfollower',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
