# Generated by Django 4.2b1 on 2023-04-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0076_alter_eventfollower_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='PASSWORD',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Publish',
        ),
    ]
