# Generated by Django 4.2b1 on 2023-04-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0077_remove_event_password_remove_event_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(default='rr', max_length=20),
            preserve_default=False,
        ),
    ]
