# Generated by Django 4.2b1 on 2023-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0084_alter_userinterest_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='User_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
