# Generated by Django 4.2b1 on 2023-04-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0085_alter_userinterest_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image10'),
        ),
        migrations.AddField(
            model_name='event',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image6'),
        ),
        migrations.AddField(
            model_name='event',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image7'),
        ),
        migrations.AddField(
            model_name='event',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image8'),
        ),
        migrations.AddField(
            model_name='event',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image9'),
        ),
    ]
