# Generated by Django 4.2b1 on 2023-05-01 14:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0086_event_image10_event_image6_event_image7_event_image8_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image9',
        ),
        migrations.AlterField(
            model_name='event',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 300], upload_to='events/', verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 300], upload_to='events/', verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 300], upload_to='events/', verbose_name='image4'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 300], upload_to='events/', verbose_name='image5'),
        ),
    ]
