# Generated by Django 4.2b1 on 2023-05-01 22:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0087_remove_event_image10_remove_event_image6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=1, size=[512, 256], upload_to='events/', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=1, size=[512, 256], upload_to='events/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=1, size=[512, 256], upload_to='events/', verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=1, size=[512, 256], upload_to='events/', verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=1, size=[512, 256], upload_to='events/', verbose_name='image4'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=1, size=[512, 256], upload_to='events/', verbose_name='image5'),
        ),
    ]
