# Generated by Django 4.2b1 on 2023-03-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_interests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
