# Generated by Django 4.2b1 on 2023-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagment', '0002_alter_publish_info_audience_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish_info',
            name='ID',
        ),
        migrations.AlterField(
            model_name='publish_info',
            name='Publication_Date',
            field=models.DateTimeField(blank=True),
        ),
    ]
