# Generated by Django 4.2b1 on 2023-05-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagment', '0003_remove_publish_info_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish_info',
            name='Publication_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
