# Generated by Django 4.2b1 on 2023-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='EVENT_ID',
            field=models.IntegerField(default=11111),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='EVENT_ID',
            field=models.IntegerField(default=11111),
        ),
    ]
