# Generated by Django 4.2b1 on 2023-03-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_discount_event_id_alter_ticket_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
