# Generated by Django 4.2b1 on 2023-03-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_ticket_id_alter_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ID',
            field=models.IntegerField(),
        ),
    ]
