# Generated by Django 4.2b1 on 2023-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='EVENT_ID',
            field=models.IntegerField(),
        ),
    ]
