# Generated by Django 4.2b1 on 2023-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('EVENT_ID', models.IntegerField()),
                ('SUB_CATEGORY_ID', models.IntegerField()),
            ],
        ),
    ]
