# Generated by Django 4.2b1 on 2023-03-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_interests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
