# Generated by Django 4.2b1 on 2023-03-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
