# Generated by Django 4.2b1 on 2023-05-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketclass',
            name='quantity_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
