# Generated by Django 4.2b1 on 2023-05-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_ticketclass_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketclass',
            name='quantity_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
