# Generated by Django 4.2b1 on 2023-03-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('F_NAME', models.CharField(max_length=20)),
                ('L_NAME', models.CharField(max_length=20)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=20)),
                ('AGE', models.IntegerField()),
                ('BIRTH_DATE', models.DateField()),
                ('PHONE', models.CharField(max_length=20)),
                ('CITY', models.CharField(max_length=20)),
                ('COUNTRY', models.CharField(max_length=20)),
                ('ADDRESS', models.CharField(max_length=20)),
                ('LOCATION_ID', models.IntegerField()),
                ('DISCOUNT_ID', models.IntegerField()),
            ],
        ),
    ]
