# Generated by Django 4.2b1 on 2023-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('TYPE', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('sub_category_id', models.IntegerField()),
            ],
        ),
    ]
