# Generated by Django 4.2b1 on 2023-03-21 10:58

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_interests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='ADDRESS',
        ),
        migrations.RemoveField(
            model_name='user',
            name='AGE',
        ),
        migrations.RemoveField(
            model_name='user',
            name='BIRTH_DATE',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CITY',
        ),
        migrations.RemoveField(
            model_name='user',
            name='COUNTRY',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EMAIL',
        ),
        migrations.RemoveField(
            model_name='user',
            name='F_NAME',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LOCATION_ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='L_NAME',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PASSWORD',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PHONE',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='dani', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='male', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='dani', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='cairo', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='egypt', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
