# Generated by Django 4.2b1 on 2023-04-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
