# Generated by Django 4.2b1 on 2023-04-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_discount_id_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='email',
            field=models.EmailField(default='ll@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
