# Generated by Django 4.2b1 on 2023-04-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customtoken_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
