# Generated by Django 4.2b1 on 2023-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('percent_off', models.IntegerField()),
                ('CODE', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Quantity_available', models.IntegerField()),
                ('User_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('NAME', models.CharField(max_length=20)),
                ('PRICE', models.FloatField()),
                ('EVENT_ID', models.IntegerField()),
                ('GUEST_ID', models.IntegerField()),
                ('TICKET_NUM', models.IntegerField()),
            ],
        ),
    ]
