# Generated by Django 4.2b1 on 2023-04-14 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_alter_event_image'),
        ('booking', '0002_discount_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Absorb_fees',
            field=models.CharField(choices=[('t', 'true'), ('f', 'false')], default='Free', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='End_time',
            field=models.DateTimeField(default='2023-05-04 5:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='Sales_end',
            field=models.DateField(default='2023-05-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='Sales_start',
            field=models.DateField(default='2023-05-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='Start_time',
            field=models.DateTimeField(default='2023-05-04 4:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='TICKET_TYPE',
            field=models.CharField(choices=[('Free', 'Free'), ('VIP', 'VIP'), ('Donation', 'Donation')], default='Free', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
            preserve_default=False,
        ),
    ]
