# Generated by Django 4.2b1 on 2023-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_discount_percent_off_discount_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='Reveal_hidden',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Ticket_limit',
            field=models.CharField(blank=True, choices=[('Limited', 'Limited'), ('Unlimited', 'Unlimited')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ticketclass',
            name='Absorb_fees',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True),
        ),
    ]
