# Generated by Django 4.2b1 on 2023-04-25 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0053_remove_event_images_delete_eventimage'),
        ('booking', '0003_ticket_absorb_fees_ticket_end_time_ticket_sales_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='GUEST_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
