# Generated by Django 4.1.8 on 2023-04-27 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0049_alter_event_id_alter_event_category_name_and_more"),
        (
            "booking",
            "0003_ticket_absorb_fees_ticket_end_time_ticket_sales_end_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="GUEST_ID",
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "tickets_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.ticket"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
