# Generated by Django 4.2b1 on 2023-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_order_orderitem_ticketclass_remove_ticket_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketclass',
            name='GUEST_ID',
        ),
        migrations.AlterField(
            model_name='ticketclass',
            name='NAME',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketclass',
            name='TICKET_TYPE',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Donation', 'Donation')], max_length=10, null=True),
        ),
    ]
