# Generated by Django 4.2b1 on 2023-04-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_ticketclass_guest_id_alter_ticketclass_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketclass',
            name='User_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
