# Generated by Django 4.2b1 on 2023-05-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_discount_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketclass',
            name='TICKET_TYPE',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Donation', 'Donation')], default='Free', max_length=10),
            preserve_default=False,
        ),
    ]
