# Generated by Django 4.2b1 on 2023-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_ticketclass_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Ends',
            field=models.CharField(blank=True, choices=[('When ticket sales end', 'When ticket sales end'), ('scheduled', 'scheduled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Starts',
            field=models.CharField(blank=True, choices=[('now', 'now'), ('scheduled', 'scheduled')], max_length=20, null=True),
        ),
    ]
